### ISSUE TITLE
Suggested Improvements

### ISSUE THREAD

**Issue by lloydk** [adamstac/font-stacks#1]
I like the function style inteface that you've used, here are some suggested improvements:
- create default variables for the five generic font families (serif, sans-serif, monospace, cursive and fantasy) 
- allow me to specify "serif", "sans-serif", "monospace", "cursive" or "fantasy" as a parameter to the font-family function to get the default stack for the specified generic family.
- add the ability to optionally print a warning if the font-family I specified isn't found.
- DRY up the mixin.
- I have to go through the code to see which font stacks are available which kinda sucks (main reason I went with variables). I'd like to be able to point a designer at a list of font stacks that they can use. Maybe create a list of font stacks as part of the readme?

**Comment by adamstac** [comment]
Thanks for the feedback Lloyd. A few you mentioned are in my plan.

But as for DRYing up the mixin, what's not dry about it?

**Comment by lloydk** [comment]
Maybe I'm missing something but couldn't the mixin be something like this:

``` scss
@mixin font-family($family) {
  font-family: font-family($family);
}
```

**Comment by adamstac** [comment]
You know what? I copied the functions to create the mixin, and I guess I thought that'd I'd need the conditionals from that in the mxins too, but now that you mention it, the functions condition handle all conditions as well as the `@warn` for when the font can't be found.

Thanks for pointing that out. The simple things.

**Comment by adamstac** [comment]
Minus the suggestions for cursive and fantasy font families, this is all in the latest (0.1.4). I'd gladly accept a pull request if you want to add those in. I won't have the time for the next week or so to circle back, so if you have time, feel free to fork and add.

Thanks for the suggestions!
