### ISSUE TITLE
How does the Ruby Gem get updated?

### ISSUE THREAD

**Issue by ElijahLynn** [adamstac/font-stacks#5]
More of a general question. If you make changes here, did you have to break off a new version for the gem hosting (http://rubygems.org/gems/font-stacks)? Or does it do it automatically?

**Comment by adamstac** [comment]
I have to rev and push it. It's manual. But easy cause there are [a few rake tasks](https://github.com/adamstac/font-stacks/blob/master/Rakefile#L13) to make it easy.

**Comment by ElijahLynn** [comment]
Cool beans. Do you setup a another remote for rubygems to push to?

**Comment by adamstac** [comment]
I'm not sure what you're asking me.

**Comment by ElijahLynn** [comment]
When you push to rubygems from the git repo on your local do you have a remote for github and another for rubygems? I guess the first question would be, do you even use git to upload to rubygems? If so do you push from the same local repo?

**Comment by adamstac** [comment]
Yea I push from the same local repo. I version, tag, then push to github and rubygems. Rinse and repeat for each new version.

**Comment by ElijahLynn** [comment]
Gotcha, thanks for explaining that, I was wondering what the workflow is like.
